create or replace view public.v_obras_painel as
 SELECT id,
    cliente,
    slug,
    telefone,
    potencia_kwp,
    contrato,
    etapa_numero,
    status,
    data_fechamento,
    data_conclusao,
    observacoes,
    criado_em,
    atualizado_em,
    whatsapp_grupo_id,
    vendedor_id,
    data_instalacao,
    instalador_id,
    instalador_token,
    aceite_assinatura,
    aceite_nome,
    aceite_documento,
    aceite_em,
    qtd_modulos,
    modelo_modulo,
    inversor_descricao,
    tipo_telhado,
    endereco,
    tem_estrutura,
    tem_cabo,
    ultimo_alerta_prazo,
    nps_token,
    nps_enviado_em,
    instalacao_lembrete_em,
    relatorio_enviado_em,
    trilha,
    categoria,
    ramo,
    cidade,
    iptu_avisado_em,
    iptu_respondido_em,
    ultima_resposta_em,
    optin_em,
    optin_texto,
    optin_origem,
    optout_em,
    optout_origem,
    nascimento_dia,
    nascimento_mes,
    aniversario_enviado_ano,
    optin_pedido_em,
    origem_lead,
    origem_detalhe,
    distancia_km,
    trava,
    trava_em,
    trava_obs,
    cpfl_solicitado_em,
    cpfl_prazo_em,
    cpfl_avisado_em,
    cobranca_fotos_qtd,
    cobranca_fotos_em,
    tipo_manutencao,
    cliente_externo,
    sistema_origem,
    data_fim,
    valor_projeto,
    aceite_pedido_em,
    aceite_cobranca_qtd,
    aceite_metodo,
    concessionaria,
    alerta_espera_em,
    solarview_id,
    cliente_id,
    CURRENT_DATE - atualizado_em::date AS dias_na_etapa,
    (EXISTS ( SELECT 1
           FROM obra_usina x
          WHERE x.obra_id = o.id)) AS tem_usina,
    (EXISTS ( SELECT 1
           FROM obra_usina x
             JOIN usina_dia d ON d.usina_id = x.usina_id
          WHERE x.obra_id = o.id AND d.kwh > 0.5 AND d.dia >= (CURRENT_DATE - 10))) AS usina_gerando,
    ( SELECT round(sum(d.kwh)) AS round
           FROM obra_usina x
             JOIN usina_dia d ON d.usina_id = x.usina_id
          WHERE x.obra_id = o.id AND d.dia >= (CURRENT_DATE - 10)) AS kwh_10d
   FROM obras o;

alter view public.v_obras_painel set (security_invoker = true);

grant select on public.v_obras_painel to authenticated;
